name: CI

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
    #test:
    #name: Test
    #runs-on: ubuntu-latest
    #steps:
    #  - name: Checkout code
    #    uses: actions/checkout@v2

    #  - name: Unit tests
    #    run: |
    #      export BASE_URL=https://scicat.ess.eu/api/v3
    #      npm ci
    #      npm test

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    #    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/panosc-eu/panosc-search-api
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=stable,enable=${{startsWith(github.ref, 'refs/tags/v')}}
            type=ref,event=tag

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_IMAGE_PUSH_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}

