name: Test

on:
  pull_request:
    branches: 
      - master
      
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        working-directory: search-api
        run: |
          npm ci
          npm run lint
          npm run test
